# Generated by Django 6.0.2 on 2026-03-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledBooking',
            fields=[
            ],
            options={
                'verbose_name': 'Cancelled Booking',
                'verbose_name_plural': 'Cancelled Bookings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.booking',),
        ),
    ]
